version: '3.3'
services:
  php:
    build:
      context: ./docker/php
    volumes:
      - './www:/var/www/html'

  nginx:
    container_name: nginx_respace
    image: nginx:latest
    volumes:
      - './www:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    ports:
      - ${SERVER_PORT}:80
    depends_on:
      - mysql

  mysql:
    container_name: mysql_respace
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - './docker/mysql:/var/lib/mysql'

  phpmyadmin:
    container_name: phpmyadmin_respace
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - ${PHP_MY_ADMIN_PORT}:80
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql